name: create pull request
inputs: 
  GITHUB_TOKEN: # id of input
    description: 'token'
    required: true
outputs:
  PR_URL:
    description: "pull request url"
    value: ${{ steps.pr_creation.outputs.URL }}

 

  
runs:
  using: composite
  steps:    
      - name: create PR
        id: pr_creation
        run: |
          pr_response=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/im-sandbox-phanirb/demo-2/pulls \
            -f title='test' \
          -f body='Please pull these awesome changes in!' \
          -f head='automated/demo-2-1695132595' \
          -f base='main')
          
           echo "$pr_response"
           echo "$response" > update_response.json
           
           
           pr_url=$(echo "$pr_response" | jq -r '.url')
           echo "$pr_url"
           echo "::set-output name=URL::$pr_url"
       
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        shell: bash
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: update_response.json
          path: ./update_response.json
        shell: bash
