name: Close Issue on Label

on:
  issues:
    types:
      - labeled

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        run: |
          issue_number="${{ github.event.issue.number }}"
          
          # Close the issue
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/im-sandbox-phanirb/demo-2/issues/$issue_number \
            -d '{"state": "closed"}'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
