name: create pull request
on:
  workflow_dispatch:

permissions: 
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: create PR
        id: trigger_pr
        uses: im-sandbox-phanirb/demo-2@main
        with: 
          GITHUB_TOKEN: ${{ secrets.USER_PAT }}

      - name: Archive Pull Request URL
        run: echo "::set-output name=pr_url::${{ steps.trigger_pr.outputs.PR_URL }}"

      - name: Verify Output
        run: |
          echo "Pull Request URL: ${{ steps.trigger_pr.outputs.PR_URL }}"
          

        
          

      
