name: create branch
on:
  workflow_dispatch:

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Generate Random Branch Name
        id: random-branch-name
        run: |
          BRANCH_NAME="automated/${GITHUB_REPOSITORY##*/}-$(date +%s)"         
          echo "::set-output name=NEW_BRANCH_NAME::$BRANCH_NAME" 
          echo "Generated BRANCH_NAME: $NEW_BRANCH_NAME"

      - name: Create New Branch
        run: |
          git checkout -b ${{ steps.random-branch-name.outputs.NEW_BRANCH_NAME }}
          git config --global push.autoSetupRemote true
          git push origin $BRANCH_NAME        
