name: create pull request
on:
  workflow_dispatch:

permissions: 
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: create PR
        id: create_pull_request
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/im-sandbox-phanirb/demo-2/pulls \
            -f title='test' \
          -f body='Please pull these awesome changes in!' \
          -f head='automated/demo-2-1694610399' \
          -f base='main' 
          
      - name: getting output
        run: |
          echo '${{ steps.create_pull_request.outputs.url }}'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

      
