name: Attach Label to Issue

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue Number'
        required: true
      label:
        description: 'Label Name'
        required: true

jobs:
  attach_label:
    runs-on: ubuntu-latest
    steps:
      - name: Attach Label
        run: |
          # Attach the label to the issue
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/im-sandbox-phanirb/demo-2/issues/${{ inputs.issue_number }}/labels \
              -d '{"labels":["${{ inputs.label }}"]}'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
