name: create pull request
on:
  workflow_dispatch:

permissions: 
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: create PR
        id: create_pull_request
        uses: im-sandbox-phanirb/demo-2@main
        with: 
          GITHUB_TOKEN: ${{ secrets.USER_PAT }}

      - name: verify output    
        run: |
          echo "${{ steps.create_pull_request.outputs.PR_URL }}
          

        
          

      
