name: create branch
on:
  workflow_dispatch:

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Generate Random Branch Name
        id: random-branch-name
        run: |
          BRANCH_NAME="automated/${GITHUB_REPOSITORY##*/}-$(date +%s)"         
          echo "::set-output name=NEW_BRANCH_NAME::$BRANCH_NAME" 
          echo "Generated BRANCH_NAME: $NEW_BRANCH_NAME"
      - name: Create New Branch
        run: |
          git checkout -b ${{ steps.random-branch-name.outputs.NEW_BRANCH_NAME }}
          git config --global push.autoSetupRemote true
          git push origin $BRANCH_NAME       
      - name: update readme file
        run: |
          ls -la
          git checkout $BRANCH_NAME
          ls -la
          cat README.md
          echo "Current Date and Time: $(date)" >> README.md
          git add .
          git commit -m "add to readme"
          git config --global push.autoSetupRemote true
          git push origin $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.USER_PAT }}

      - name: create pull request
        run: |
          curl -X POST \
            -H "Authorization: token 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" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/<im-sandbox-phanirb/demo-2/pulls \
            -d '{
              "title": "update readme",
              "head": "automated/demo-2-1694614983",
              "base": "main",
              "body": "created new branch and updated readme file"
            }'
