name: create pull request
on:
  workflow_dispatch:

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: checkout of branch
        run: |
          #git config user.name "GitHub Actions"
          #git config user.email noreply@github.com
          git branch
          #git checkout -b automated/demo-2-1694614983
          #git config --global push.autoSetupRemote true
          #git push origin automated/demo-2-1694614983
        
      - name: Create Pull Request        
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.USER_PAT }}
            branch: automated/demo-2-1694614983
            base: main           
            title: "update readme"
            body: "created new branch and updated readme file"
