name: Close Issue

on:
  workflow_run:
    workflows: ["Issue comment using API"]
    types:
      - completed

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Latest Issue Number
        id: get_latest_issue
        run: |
          latest_issue=$(gh api /repos/${{ github.repository }}/issues?state=all | jq '.[0]')
          latest_issue_number=$(echo "$latest_issue" | jq -r '.number')
          echo "::set-output name=latest_issue_number::$latest_issue_number"

      - name: Close Latest Issue
        if: steps.get_latest_issue.outputs.latest_issue_number
        run: |
          latest_issue_number="${{ steps.get_latest_issue.outputs.latest_issue_number }}"
          gh api -X PATCH /repos/${{ github.repository }}/issues/${latest_issue_number} -f state=closed
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
