name: Close Issue

on:
  workflow_run:
    workflows: ["Issue comment using API"]
    types:
      - completed

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue Number from Comment
        id: get_issue_number
        run: |
          issue_number=$(gh api \
            --method GET \
            /repos/${ORGANIZATION}/${REPOSITORY}/issues/${{ github.event.workflow_run.payload.comment.body | split: ': ' | last | trim }} \
            --jq '.number')
          echo "::set-output name=issue_number::${issue_number}"

      - name: Close Issue
        run: |
          gh api -X PATCH \
          https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${{ steps.get_issue_number.outputs.issue_number }} \
          -f state=closed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organization.login }}
          REPOSITORY: ${{ github.event.repository.name }}
